name: SurvivalHeaven-CORE
version: '0.1.5-SNAPSHOT ( impl: v1_8_R1 )'
main: info.nordbyen.survivalheaven.SH
depend: [ WorldEdit, BlocksHub ] 
commands:
  infdisp: 
    description: "Lager en uendelig dispenser"